### ISSUE TITLE
Integration with WatchGuard Firewall fails

### ISSUE THREAD

**Issue by bfolberth** [token2/TOTPRadius#32]
Trying to integrate TOTPRadius with WatchGuard Firewall fails for me. From the TOTPRadiums logs point of view everything seems fine (user successfully authenticated), but in total authentication fails. WatchGuard Firewall logs state "was rejected, user isn't in the right group". But I'm pretty sure the user is in the right group as when I switch TOTPRadius for another solution this works fine. Any idea?

**Comment by token2** [comment]
Hello Bernd, and thanks for your interest
 TOTPRadius does not return any attributes by default. WatchGuard seems to require Filter-ID in the radius response:
>When the Firebox gets the Access-Accept message from RADIUS, it reads the value of the FilterID attribute and uses this value to associate the user with a RADIUS group. (You must manually configure the FilterID in your RADIUS configuration.) Thus, the value of the FilterID attribute is the name of the RADIUS group where the device puts the user.
https://www.watchguard.com/help/docs/help-center/en-US/Content/en-US/Fireware/authentication/radius_how_works_c.html

 As a workaround, you can follow this:

- Login to your appliance via SSH (if this the first time the appliance boots up, hit Control+C in the console to cancel the config wizard and proceed with RSA key generation, otherwise SSHD will not start) - Default user is totpradius:totpradius

- Edit the file /etc/freeradius/3.0/sites-enabled/default and after this code

> update control {
>   Auth-Type := "/usr/bin/php /var/www/radius.php %{User-Name} %{User-Password} ",
>              }

add the following

>update reply {
>        Filter-ID :=  "Company:version=1:policy=staff"
>        }

Save the file and restart the service (you can restart from Admin panel or from SSH). After this, TOTPRadius will return Filter-ID attribute, in addition, to Accept/Reject message. It should look like below:
>Sent Access-Request Id 248 from 0.0.0.0:55870 to 127.0.0.1:1812 length 79
        User-Name = "totptest"
        User-Password = "739796"
        NAS-IP-Address = 127.0.0.1
        NAS-Port = 1812
        Message-Authenticator = 0x00
        Cleartext-Password = "739796"
Received Access-Accept Id 248 from 127.0.0.1:1812 to 0.0.0.0:0 length 55
        Filter-Id = "TOTPRADIUS:version=1:policy=staff"


Unfortunately, we do not have a possibility to check this as we do not have WatchGuard Firewall available. Grateful if you can try and let us know. Thanks in advance
